# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - searchim

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d9437d8e17e84bb7b8ad005eaf04b66c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_71c58cc6f0f1420bad212d621a4fb3f1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d9437d8e17e84bb7b8ad005eaf04b66c }}/search-engine:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'searchim'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_65213326219a4fc58c47dbb2442efcd5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d9437d8e17e84bb7b8ad005eaf04b66c }}/search-engine:${{ github.sha }}'